### ISSUE TITLE
License ambiguity

### ISSUE THREAD

**Issue by chrysn** [openwsn-berkeley/edhoc-rs#152]
The `license = "..."` fields of the crates contain the identifier "BSD", which is not a recognized SPDX identifier ([even though that's the list into which that key maps](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields)).

From the LICENSE.md file, my best guess is that you intend to put "BSD-3-Clause" in there. When addressed after #146, this can easily be addressed widely by placing a license term in the workspace Cargo.toml, and linking it from the individual crates using `license.workspace = true`.

**Comment by malishav** [comment]
Yes, confirming BSD-3-Clause is the right license.

**Comment by geonnave** [comment]
Solved in #146
