### ISSUE TITLE
CoAP server's behavior on requests targeting unknown CoAP resources

### ISSUE THREAD

**Issue by actyp** [openwsn-berkeley/edhoc-rs#77]
EDHOC-Fuzzer's learned model of the CoAP server (commit 09aa2a8) exposes the following behavior on **messages sent to unknown/unsupported CoAP resources**. Below, we present three cases, **before**, **during** and **after** an EDHOC exchange.

### 09aa2a8 Server Test: Messages sent to an unsupported CoAP Resource of the server BEFORE an EDHOC exchange
```
    CLIENT            SERVER
(EDHOC-Fuzzer)    (Under Testing)
      |------  APPc  ----->| * GET request with no payload
      |<-----  EMPc  ------| * Empty CoAP message (with no payload)
      |------  APPo  ----->| * Dummy OSCORE message
      |<-----  APPc  ------| * CoAP message with payload the payload of the OSCORE message
      |------ M3APPo ----->| * Combined a dummy EDHOC Message 3 and a dummy OSCORE message
      |<-----  APPc  ------| * CoAP message with payload the payload of the combined message
```

#### Messages used

* APPc [From the EDHOC-Fuzzer] (CoAP app message non-OSCORE protected, which in this case is a GET request)
* EMPc (Empty CoAP message, which means it has no payload)
* APPo (OSCORE protected app message, which in this case is a protected GET request)
* APPc [From the server] (CoAP app message non-OSCORE protected)
* M3APPo (EDHOC Message 3 combined with an OSCORE protected app message, which in this case is a protected GET request)

The APPc, APPo, M3APPo messages are sent to a default CoAP resource 'applicationEndpoint', unknown to the server.

### 09aa2a8 Server Test: Messages sent to an unsupported CoAP Resource of the server DURING an EDHOC exchange
```
    CLIENT            SERVER
(EDHOC-Fuzzer)    (Under Testing)
      |------   M1   ----->| * EDHOC Message 1 from EDHOC-Fuzzer
      |<-----   M2   ------| * EDHOC Message 2 from server
      |------  APPc  ----->| * GET request with no payload
      |<-----  EMPc  ------| * Empty CoAP message (with no payload)
      |------  APPo  ----->| * Dummy OSCORE message
      |<-----  APPc  ------| * CoAP message with payload the payload of the OSCORE message
      |------ M3APPo ----->| * Combined the expected EDHOC Message 3 and a dummy OSCORE message
      |<-----  APPc  ------| * CoAP message with payload the payload of the combined message
```

#### Messages used

* M1 (EDHOC Message 1)
* M2 (EDHOC Message 2)
* APPc [From the EDHOC-Fuzzer] (CoAP app message non-OSCORE protected, which in this case is a GET request)
* EMPc (Empty CoAP message, which means it has no payload)
* APPo (OSCORE protected app message, which in this case is a protected GET request)
* APPc [From the server] (CoAP app message non-OSCORE protected)
* M3APPo (EDHOC Message 3 combined with an OSCORE protected app message, which in this case is a protected GET request)

The APPc, APPo, M3APPo messages are sent to a default CoAP resource 'applicationEndpoint', unknown to the server.

### 09aa2a8 Server Test: Messages sent to an unsupported CoAP Resource of the server AFTER an EDHOC exchange
```
    CLIENT            SERVER
(EDHOC-Fuzzer)    (Under Testing)
      |------   M1   ----->| * EDHOC Message 1 from EDHOC-Fuzzer
      |<-----   M2   ------| * EDHOC Message 2 from server
      |------   M3   ----->| * EDHOC Message 3 from EDHOC-Fuzzer
      |<-----  EMPc  ------| * The EDHOC exchange is completed
      |------  APPc  ----->| * GET request with no payload
      |<-----  EMPc  ------| * Empty CoAP message (with no payload)
      |------  APPo  ----->| * Dummy OSCORE message
      |<-----  APPc  ------| * CoAP message with payload the payload of the OSCORE message
      |------ M3APPo ----->| * Combined the expected EDHOC Message 3 and a dummy OSCORE message
      |<-----  APPc  ------| * CoAP message with payload the payload of the combined message
```

#### Messages used

* M1 (EDHOC Message 1)
* M2 (EDHOC Message 2)
* M3 (EDHOC Message 3)
* APPc [From the EDHOC-Fuzzer] (CoAP app message non-OSCORE protected, which in this case is a GET request)
* EMPc (Empty CoAP message, which means it has no payload)
* APPo (OSCORE protected app message, which in this case is a protected GET request)
* APPc [From the server] (CoAP app message non-OSCORE protected)
* M3APPo (EDHOC Message 3 combined with an OSCORE protected app message, which in this case is a protected GET request)

The APPc, APPo, M3APPo messages are sent to a default CoAP resource 'applicationEndpoint', unknown to the server.

### Accompanying Files

We can also provide you with the server's log and a wireshark capture for each one of these interactions (either in this issue or via email).

### Observed Behavior

The server responds to APPc, APPo, M3APPo messages with a CoAP message that contains as payload the payload of the request. It is possible that this is the default behavior of the CoAP library used in edhoc-rs when a request to an unknown resource is received.

### Some Questions

 * Can you confirm this behavior?
 * Were you aware of it?
 * Is it intentional or an oversight?
 * Would it not be more appropriate for the server to either ignore the message targeting an unknown CoAP resource or reply with a CoAP error message?

**Comment by malishav** [comment]
Thanks for reporting, we are looking into it!
