### ISSUE TITLE
Improve parsing robustness

### ISSUE THREAD

**Issue by malishav** [openwsn-berkeley/edhoc-rs#92]
A [PR on draft-ietf-lake-traces](https://github.com/lake-wg/edhoc/pull/442) adds several invalid test vectors. In edhoc-rs, these pass the `parse_message_1` routine normally, which should not happen as it should return an error. This issue aims at improving the robustness of parsing of message_1 and message_2 in order to check for incorrect CBOR messages.

**Comment by geonnave** [comment]
Solved in #95.
